#!/usr/bin/env python3
"""Build a deterministic AgentsServer release archive and manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import tarfile
import tempfile
from pathlib import Path


FILES = (
    "agent_server.py",
    "team_hub_host.py",
    "secure_peer_runtime.py",
    "secure_peer_delivery.py",
    "agentsdock_jobs.py",
    "agentsdock_chats.py",
    "agentsdock_publish.py",
    "claude_sdk_client.py",
    "codex_app_server.py",
    "install.sh",
    "uninstall.sh",
    "update_runner.py",
    "pyproject.toml",
    "uv.lock",
    "VERSION",
    "release-public-key.pem",
)

DIRECTORY_FILES = {
    "agentsdock_team_hub": (
        "__init__.py",
        "auth.py",
        "cli.py",
        "database.py",
        "security.py",
        "secure_peer.py",
        "secure_peer_hub.py",
        "service.py",
        "store.py",
        "migrations/__init__.py",
        "migrations/0001_identity_auth.sql",
        "migrations/0002_teamspace_ledger.sql",
        "migrations/0003_service_runtime.sql",
        "migrations/0004_managed_host_binding.sql",
        "migrations/0005_tailnet_bootstrap_delegations.sql",
        "migrations/0006_team_network_mailbox.sql",
    ),
}
DIRECTORIES = tuple(DIRECTORY_FILES)


def validate_release_files(root: Path) -> None:
    """Require every top-level release member to be a real regular file."""

    linked = [name for name in FILES if (root / name).is_symlink()]
    if linked:
        raise SystemExit(f"linked release files are not allowed: {', '.join(linked)}")
    missing = [name for name in FILES if not (root / name).is_file()]
    if missing:
        raise SystemExit(f"missing release files: {', '.join(missing)}")


def validate_release_directory(path: Path) -> None:
    """Reject generated, linked, or special entries from packaged modules."""

    if not path.is_dir() or path.is_symlink():
        raise SystemExit(f"missing release directory: {path.name}")
    for entry in path.rglob("*"):
        relative = entry.relative_to(path)
        if entry.is_symlink():
            raise SystemExit(
                f"release directory contains a symlink: {path.name}/{relative}"
            )
        if entry.is_dir():
            if entry.name == "__pycache__":
                raise SystemExit(
                    f"release directory contains generated bytecode: {path.name}/{relative}"
                )
            continue
        if not entry.is_file():
            raise SystemExit(
                f"release directory contains a special file: {path.name}/{relative}"
            )
        if entry.suffix in {".pyc", ".pyo"}:
            raise SystemExit(
                f"release directory contains generated bytecode: {path.name}/{relative}"
            )
    actual = {
        entry.relative_to(path).as_posix()
        for entry in path.rglob("*")
        if entry.is_file()
    }
    expected = set(DIRECTORY_FILES[path.name])
    missing = sorted(expected - actual)
    unexpected = sorted(actual - expected)
    if missing:
        raise SystemExit(
            f"release directory is missing required files: {path.name}/"
            + f", {path.name}/".join(missing)
        )
    if unexpected:
        raise SystemExit(
            f"release directory contains unexpected files: {path.name}/"
            + f", {path.name}/".join(unexpected)
        )
    actual_directories = {
        entry.relative_to(path).as_posix()
        for entry in path.rglob("*")
        if entry.is_dir()
    }
    expected_directories = {
        parent.as_posix()
        for name in expected
        for parent in Path(name).parents
        if parent != Path(".")
    }
    unexpected_directories = sorted(actual_directories - expected_directories)
    if unexpected_directories:
        raise SystemExit(
            f"release directory contains unexpected directories: {path.name}/"
            + f", {path.name}/".join(unexpected_directories)
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="dist")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    version = (root / "VERSION").read_text().strip()
    output = (root / args.output).resolve()
    output.mkdir(parents=True, exist_ok=True)
    archive_name = f"agents-server-{version}.tar.gz"
    archive_path = output / archive_name

    validate_release_files(root)
    for name in DIRECTORIES:
        validate_release_directory(root / name)
    with tempfile.TemporaryDirectory(prefix="agents-server-package-") as temporary:
        package_root = Path(temporary) / f"agents-server-{version}"
        package_root.mkdir()
        for name in FILES:
            target = package_root / name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(root / name, target)
        for name in DIRECTORIES:
            shutil.copytree(root / name, package_root / name, symlinks=False)
        (package_root / "install.sh").chmod(0o755)
        (package_root / "uninstall.sh").chmod(0o755)
        (package_root / "agentsdock_jobs.py").chmod(0o755)
        (package_root / "agentsdock_chats.py").chmod(0o755)
        (package_root / "agentsdock_publish.py").chmod(0o755)
        (package_root / "update_runner.py").chmod(0o755)
        with tarfile.open(archive_path, "w:gz", format=tarfile.PAX_FORMAT) as archive:
            archive.add(package_root, arcname=package_root.name)

    commit = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=root, capture_output=True, text=True, check=False
    ).stdout.strip()
    manifest = {
        "schema": 1,
        "version": version,
        "track": "beta" if "-" in version.split("+", 1)[0] else "stable",
        "prerelease": "-" in version.split("+", 1)[0],
        "api_contract_version": 15,
        "commit": commit,
        "archive": {
            "name": archive_name,
            "url": f"https://github.com/ZhengyiLuo/AgentsServer/releases/download/v{version}/{archive_name}",
            "sha256": hashlib.sha256(archive_path.read_bytes()).hexdigest(),
            "size": archive_path.stat().st_size,
        },
    }
    (output / "agents-server-manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    print(archive_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
